import { describe, expect, it } from 'vitest';
import { buildStaticHtml, slugifyPageSlug } from './websiteService';
import { WebsitePage } from '../types';

const samplePage: WebsitePage = {
  title: 'Test Landing Page',
  slug: 'test-landing-page',
  content: {
    headline: 'Grow faster with AI',
    subheadline: 'Automate lead capture and follow-up with BuildMyBot.',
    features: ['Instant AI bot', 'SEO friendly', 'Embeddable widget'],
    ctaText: 'Start Free'
  },
  seoMetadata: {
    title: 'AI Landing Page | BuildMyBot',
    description: 'High-converting page generated by BuildMyBot.',
    keywords: ['ai', 'landing page', 'seo']
  },
  published: false
};

describe('slugifyPageSlug', () => {
  it('lowercases and trims unsafe characters', () => {
    expect(slugifyPageSlug('Hello World!')).toBe('hello-world');
    expect(slugifyPageSlug('  MULTI   space ')).toBe('multi-space');
    expect(slugifyPageSlug('123___Test')).toBe('123-test');
  });

  it('falls back to a default slug when empty', () => {
    expect(slugifyPageSlug('!!!')).toBe('page');
  });
});

describe('buildStaticHtml', () => {
  it('renders SEO metadata and page content into HTML', () => {
    const html = buildStaticHtml(samplePage);

    expect(html).toContain('<title>AI Landing Page | BuildMyBot</title>');
    expect(html).toContain('meta name="description"');
    expect(html).toContain('meta name="keywords"');
    expect(html).toContain(samplePage.content.headline);
    expect(html).toContain(samplePage.content.features?.[0] || '');
    expect(html).toContain(samplePage.content.ctaText || '');
  });
});
