import React, { useState } from 'react';
import { Bot, Zap, CheckCircle, BarChart, Globe, ArrowRight, Shield, Star, Crown, FileText, Lock, X } from 'lucide-react';
import { PLANS } from '../../constants';
import { PlanType } from '../../types';

interface LandingProps {
  onLogin: () => void;
}

export const LandingPage: React.FC<LandingProps> = ({ onLogin }) => {
  const [modalContent, setModalContent] = useState<'privacy' | 'terms' | null>(null);

  const openModal = (type: 'privacy' | 'terms') => setModalContent(type);
  const closeModal = () => setModalContent(null);

  const LegalModal = () => {
    if (!modalContent) return null;
    return (
      <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[80vh] overflow-y-auto">
          <div className="p-6 border-b border-slate-200 flex justify-between items-center sticky top-0 bg-white">
            <h3 className="text-xl font-bold text-slate-800">{modalContent === 'privacy' ? 'Privacy Policy' : 'Terms of Service'}</h3>
            <button onClick={closeModal} className="p-2 hover:bg-slate-100 rounded-full"><X size={20} /></button>
          </div>
          <div className="p-8 text-slate-600 text-sm leading-relaxed space-y-4">
             {modalContent === 'privacy' ? (
               <>
                 <p><strong>Last Updated: May 20, 2024</strong></p>
                 <p>At BuildMyBot, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclosure, and safeguard your information when you visit our website including any other media form, media channel, mobile website, or mobile application related or connected thereto.</p>
                 <h4 className="font-bold text-slate-800">1. Collection of Data</h4>
                 <p>We collect information you provide directly to us when you register an account, create a bot, or contact support. This includes your name, email address, and conversation logs generated by your chatbots.</p>
                 <h4 className="font-bold text-slate-800">2. Use of Data</h4>
                 <p>We use the collected data to provide and maintain our Service, notify you about changes to our Service, and allow you to participate in interactive features of our Service when you choose to do so.</p>
                 <h4 className="font-bold text-slate-800">3. Conversation Privacy</h4>
                 <p>Chat logs are stored securely and encrypted at rest. We do not sell conversation data to third parties. Data is used solely to display analytics to the account owner.</p>
                 <p>Contact us at privacy@buildmybot.app for any questions.</p>
               </>
             ) : (
               <>
                 <p><strong>Last Updated: May 20, 2024</strong></p>
                 <h4 className="font-bold text-slate-800">1. Agreement to Terms</h4>
                 <p>These Terms of Service constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and BuildMyBot (“we,” “us” or “our”), concerning your access to and use of the BuildMyBot website.</p>
                 <h4 className="font-bold text-slate-800">2. Acceptable Use</h4>
                 <p>You agree not to use the site for any unlawful purpose or any purpose prohibited under this clause. You agree not to use the site in any way that could damage the site, the services, or the general business of BuildMyBot.</p>
                 <h4 className="font-bold text-slate-800">3. Conversation Limits</h4>
                 <p>Our service plans are based on "Conversations". A conversation is defined as a single interaction session between a bot and a user. We reserve the right to throttle or suspend bots that exhibit abusive behavior or malicious loops designed to artificially inflate costs.</p>
                 <p>Contact us at legal@buildmybot.app for any questions.</p>
               </>
             )}
          </div>
          <div className="p-6 border-t border-slate-200 bg-slate-50 flex justify-end">
            <button onClick={closeModal} className="px-4 py-2 bg-blue-900 text-white rounded-lg hover:bg-blue-950">Close</button>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 overflow-x-hidden">
      {modalContent && <LegalModal />}
      
      {/* Navbar */}
      <nav className="fixed w-full bg-white/80 backdrop-blur-md z-40 border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 font-bold text-xl text-slate-900">
            <div className="w-8 h-8 bg-blue-900 rounded-lg flex items-center justify-center text-white shadow-md">
              <Bot size={20} />
            </div>
            BuildMyBot.app
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-slate-600">
            <a href="#features" className="hover:text-blue-900 transition">Features</a>
            <a href="#pricing" className="hover:text-blue-900 transition">Pricing</a>
            <a href="#resellers" className="hover:text-blue-900 transition">Agencies</a>
          </div>
          <div className="flex items-center gap-4">
             <button onClick={onLogin} className="text-sm font-medium text-slate-600 hover:text-blue-900 hidden md:block">Log in</button>
             <button onClick={onLogin} className="px-5 py-2 bg-blue-900 text-white rounded-lg text-sm font-bold hover:bg-blue-950 transition shadow-lg shadow-blue-900/30">
               Get Started Free
             </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-7xl mx-auto text-center">
           <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-100 text-blue-900 text-xs font-bold uppercase tracking-wide mb-6">
             <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></span>
             New: AI Website Builder Included
           </div>
           <h1 className="text-5xl md:text-7xl font-extrabold text-slate-900 tracking-tight mb-2">
             Build AI Chatbots for <br/> 
             <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-900 to-sky-700">Any Business in Seconds</span>
           </h1>
           
           <h2 
             className="text-3xl md:text-5xl font-black text-slate-800 tracking-wider mb-10 uppercase opacity-90"
             style={{ WebkitTextStroke: '0px' }}
           >
             Professional White-Label AI
           </h2>

           <p className="text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
             The ultimate white-label AI platform. Create intelligent bots, generate leads, and resell to your own clients.
           </p>
           <div className="flex flex-col md:flex-row items-center justify-center gap-4 mb-16">
              <button onClick={onLogin} className="w-full md:w-auto px-8 py-4 bg-blue-900 text-white rounded-xl text-lg font-bold hover:bg-blue-950 transition shadow-xl shadow-blue-900/40 flex items-center justify-center gap-2">
                Start Building Free <ArrowRight size={20} />
              </button>
              <button onClick={onLogin} className="w-full md:w-auto px-8 py-4 bg-white text-slate-700 border border-slate-200 rounded-xl text-lg font-bold hover:bg-slate-50 transition flex items-center justify-center gap-2">
                View Demo
              </button>
           </div>
           
           {/* UI Mockup */}
           <div className="relative max-w-5xl mx-auto">
              <div className="absolute -inset-1 bg-gradient-to-r from-blue-800 to-slate-900 rounded-2xl blur opacity-20"></div>
              <div className="relative bg-white rounded-xl border border-slate-200 shadow-2xl overflow-hidden">
                <div className="h-10 bg-slate-50 border-b border-slate-200 flex items-center px-4 gap-2">
                   <div className="w-3 h-3 rounded-full bg-slate-300"></div>
                   <div className="w-3 h-3 rounded-full bg-slate-300"></div>
                   <div className="w-3 h-3 rounded-full bg-slate-300"></div>
                </div>
                <div className="aspect-[16/9] bg-slate-50 flex items-center justify-center text-slate-300">
                  <div className="text-center">
                    <Bot size={64} className="mx-auto mb-4 text-blue-200" />
                    <span className="font-semibold text-slate-400">Dashboard Preview</span>
                  </div>
                </div>
              </div>
           </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-10 border-y border-slate-200 bg-white">
         <div className="max-w-7xl mx-auto px-6 text-center">
            <p className="text-sm font-semibold text-slate-400 uppercase tracking-widest mb-6">Trusted by 2,000+ Agencies & Businesses</p>
            <div className="flex flex-wrap justify-center items-center gap-12 opacity-50 grayscale hover:grayscale-0 transition-all duration-500">
               {['Acme Corp', 'GlobalTech', 'Nebula Inc', 'FoxRun', 'Circle'].map(b => (
                 <span key={b} className="text-xl font-bold text-slate-800">{b}</span>
               ))}
            </div>
         </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="py-24 px-6 bg-slate-50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Everything you need to scale</h2>
            <p className="text-lg text-slate-600">From solo founders to enterprise agencies, we have you covered.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { icon: Zap, title: "Zero-Code Builder", desc: "Drag, drop, and train your bot on PDFs, websites, or text files in seconds." },
              { icon: Globe, title: "AI Website Generator", desc: "Create full landing pages with embedded bots automatically. SEO ready." },
              { icon: Shield, title: "White-Label Ready", desc: "Your brand, your domain, your pricing. We are invisible to your clients." },
              { icon: BarChart, title: "Advanced Analytics", desc: "Track conversations, sentiment, and user journeys in real-time." },
              { icon: Bot, title: "Multi-Model Support", desc: "Powered by Gemini 1.5 Flash & Pro for lightning fast, accurate responses." },
              { icon: CheckCircle, title: "Lead CRM", desc: "Capture emails and phone numbers directly into a built-in CRM." },
            ].map((f, i) => (
              <div key={i} className="bg-white p-8 rounded-2xl border border-slate-200 hover:border-blue-900 transition shadow-sm hover:shadow-md group">
                 <div className="w-12 h-12 bg-blue-50 text-blue-900 rounded-lg flex items-center justify-center mb-6 group-hover:scale-110 transition">
                   <f.icon size={24} />
                 </div>
                 <h3 className="text-xl font-bold text-slate-900 mb-3">{f.title}</h3>
                 <p className="text-slate-600 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 px-6 bg-white">
        <div className="max-w-[90rem] mx-auto">
           <div className="text-center mb-16">
             <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Simple, Transparent Pricing</h2>
             <p className="text-lg text-slate-600">Pay per conversation (session). No hidden per-message fees.</p>
           </div>

           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-6">
              {Object.entries(PLANS).map(([key, plan]: [string, any]) => {
                const isEnterprise = key === PlanType.ENTERPRISE;
                const isProfessional = key === PlanType.PROFESSIONAL;

                return (
                  <div key={key} className={`p-8 rounded-2xl border flex flex-col transition-all hover:shadow-xl ${
                    isProfessional 
                      ? 'border-blue-900 shadow-xl ring-1 ring-blue-900 relative z-10 scale-105' 
                      : isEnterprise
                        ? 'border-slate-800 bg-slate-900 text-white'
                        : 'border-slate-200 bg-slate-50'
                  }`}>
                    {isProfessional && (
                      <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-blue-900 text-white px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide">Most Popular</div>
                    )}
                    {isEnterprise && (
                      <div className="mb-2 inline-flex items-center gap-1 text-yellow-400 font-bold text-xs uppercase tracking-wide"><Crown size={12} fill="currentColor"/> Ultimate Power</div>
                    )}
                    
                    <h3 className={`text-lg font-bold ${isEnterprise ? 'text-white' : 'text-slate-900'}`}>{plan.name}</h3>
                    <div className="mt-4 mb-6">
                      <span className={`text-4xl font-extrabold ${isEnterprise ? 'text-white' : 'text-slate-900'}`}>${plan.price}</span>
                      <span className={`${isEnterprise ? 'text-slate-400' : 'text-slate-500'}`}>/mo</span>
                    </div>
                    
                    <ul className="space-y-4 mb-8 flex-1">
                      <li className={`flex items-center gap-3 text-sm ${isEnterprise ? 'text-slate-300' : 'text-slate-700'}`}>
                        <CheckCircle size={16} className={`${isEnterprise ? 'text-yellow-400' : 'text-emerald-500'} shrink-0`}/> 
                        {plan.bots >= 9999 ? 'Unlimited' : plan.bots} Bot(s)
                      </li>
                      <li className={`flex items-center gap-3 text-sm ${isEnterprise ? 'text-slate-300' : 'text-slate-700'}`}>
                        <CheckCircle size={16} className={`${isEnterprise ? 'text-yellow-400' : 'text-emerald-500'} shrink-0`}/> 
                        <span className="font-bold">{plan.conversations.toLocaleString()}</span>&nbsp;Conversations
                      </li>
                      <li className={`flex items-center gap-3 text-sm ${isEnterprise ? 'text-slate-300' : 'text-slate-700'}`}>
                        <CheckCircle size={16} className={`${isEnterprise ? 'text-yellow-400' : 'text-emerald-500'} shrink-0`}/> 
                        {isEnterprise ? 'Enterprise Analytics' : 'Basic Analytics'}
                      </li>
                      {isEnterprise && (
                        <>
                           <li className="flex items-center gap-3 text-sm text-slate-300">
                             <CheckCircle size={16} className="text-yellow-400 shrink-0"/> White-label Ready
                           </li>
                           <li className="flex items-center gap-3 text-sm text-slate-300">
                             <CheckCircle size={16} className="text-yellow-400 shrink-0"/> SLA Support
                           </li>
                           <li className="flex items-center gap-3 text-sm text-slate-300">
                             <CheckCircle size={16} className="text-yellow-400 shrink-0"/> ${plan.overage}/overage conv
                           </li>
                        </>
                      )}
                    </ul>
                    
                    <button onClick={onLogin} className={`w-full py-3 rounded-lg font-bold transition ${
                      isProfessional 
                        ? 'bg-blue-900 text-white hover:bg-blue-950' 
                        : isEnterprise
                          ? 'bg-white text-slate-900 hover:bg-slate-200'
                          : 'bg-white text-slate-900 border border-slate-300 hover:bg-slate-50'
                    }`}>
                      {isEnterprise ? 'Get Enterprise' : `Choose ${plan.name}`}
                    </button>
                  </div>
                );
              })}
           </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 py-16 px-6">
        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-12">
           <div className="col-span-1 md:col-span-1">
             <div className="flex items-center gap-2 font-bold text-xl text-white mb-4">
                <div className="w-8 h-8 bg-blue-900 rounded-lg flex items-center justify-center text-white">
                  <Bot size={20} />
                </div>
                BuildMyBot
             </div>
             <p className="text-sm">Automating business communications one bot at a time.</p>
           </div>
           <div>
             <h4 className="text-white font-bold mb-4">Product</h4>
             <ul className="space-y-2 text-sm">
               <li><a href="#features" className="hover:text-white">Features</a></li>
               <li><a href="#pricing" className="hover:text-white">Pricing</a></li>
               <li><button onClick={onLogin} className="hover:text-white">Login</button></li>
             </ul>
           </div>
           <div>
             <h4 className="text-white font-bold mb-4">Legal</h4>
             <ul className="space-y-2 text-sm">
               <li><button onClick={() => openModal('privacy')} className="hover:text-white">Privacy Policy</button></li>
               <li><button onClick={() => openModal('terms')} className="hover:text-white">Terms of Service</button></li>
             </ul>
           </div>
           <div>
             <h4 className="text-white font-bold mb-4">Contact</h4>
             <p className="text-sm mb-2">support@buildmybot.app</p>
             <div className="flex gap-4 mt-4">
               {/* Social Icons Placeholder */}
               <div className="w-8 h-8 bg-slate-800 rounded flex items-center justify-center hover:bg-slate-700 cursor-pointer">X</div>
               <div className="w-8 h-8 bg-slate-800 rounded flex items-center justify-center hover:bg-slate-700 cursor-pointer">In</div>
             </div>
           </div>
        </div>
        <div className="max-w-7xl mx-auto mt-12 pt-8 border-t border-slate-800 text-center text-xs">
          © 2024 BuildMyBot.app. All rights reserved.
        </div>
      </footer>
    </div>
  );
};